[ai-bridge]
exten => s,1,NoOp(Starting AI Bridge)
 same => n,Set(CHANNEL(audioreadformat)=slin)
 same => n,Set(CHANNEL(audiowriteformat)=slin)
 same => n,System(curl "http://127.0.0.1:8001/api/bridge/register-caller?uuid=${CHANNEL(audioprocessuuid)}&caller=${CALLERID(num)}&ivr_key=1")
 same => n,Wait(0.5)
 same => n,AudioSocket(d7616616-2d0a-11ef-9366-00155d045a55,127.0.0.1:9092)
 same => n,Hangup()
